name: CI
on:
  push:
  pull_request:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nbclient nbconvert flake8

      - name: Lint (only smoke; ignore F401/E401 here)
        run: flake8 --ignore=F401,E401 labs/00_smoke

      - name: Run smoke (notebook)
        run: |
          jupyter nbconvert --to notebook --execute --inplace \
            --ExecutePreprocessor.timeout=120 labs/00_smoke/smoke.ipynb
